name: Deploy Roave site

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: touch .env
      - run: npm install
      - run: npm run build
      - run: mkdir pub && rm dist/.gitignore && cp -avf -t pub dist index.html favicon.ico
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: pub
          CLEAN: true
